#include <stdio.h>
/* 1. Write a program in C to demonstrate the use of &(address of) and *(value at address) operator.

# while working with pointer we need two unary operator
    1. & -> Address Operator : with the help of this operator we can find address
    2. * - > Asterisk Opeator : with the help of this operator print the value that is hold the
             address of variable....
 */

void main()
{
    int a = 10;      // here we take integer value a = 10....

    int *ptr1;       //*ptr1 is pointer variable.....
    int **ptr2;      //**ptr2 is double pointer variablr.....

    ptr1 = &a;       // ptr1 = &a  it means ptr1 is hold the address of variable a....
    ptr2 = &ptr1;    // ptr2 = &ptr1 it means ptr2 pointer variable hold the address of another pointer which is ptr1....


    printf("value of a is : %d\n", a); // a = 10

    printf("Address of variable a is : %p\n\n", &a); // print address of 'a' using & operator....
                                                     //  a =    0x7fff98ada998....

    // print the value of variable 'a' with the help of pointer variable '*ptr1'....
    printf("The Value of variable a is : %d\n", *ptr1); // a = 10....

    // here print the address of variable 'a' using pointer variable 'ptr1'.....
    printf("Address of variable a is : %p\n", ptr1); // ptra = 0x7fff98ada998

    // print the address of pointer variable (its own address)....
    printf("\n\nThe Address of ptr1 is : %p\n\n", &ptr1); // 0x7ffc2cf72cc0

    // print the value of variable 'a' using double pointer  'ptr2'....
    printf("The value of a is : %d\n", **ptr2);  // a = 10....      

    //print the address of 'ptr1' with the help of 'ptr2'.... 
    printf("Address of variable a is : %p\n\n", ptr2);  // a = 0x7ffec0d98c78
    
    //print the address of the 'ptr2' (its own address)....
    printf("\n\nThe Address of ptr1 is : %p\n\n", &ptr2);
}